namespace HttpClientGenerator.Internals
{
    public static class ClientClassTemplate
    {
        public const string Namespace = "$NAMESPACE$";
        public const string ClassName = "$CLASSNAME$";
        public const string ClassBody = "$CLASSBODY$";
        public const string ImportNamespaces = "$IMPORTNAMESPACES$";

        public const string ClassTemplateWithHttpClientDependency = @"
// <auto-generated>
//     This code was generated by HttpClientCodeGenerator.
// </auto-generated>

using System;
using System.Net.Http;
using System.Threading.Tasks;
using System.Collections.Generic;
$IMPORTNAMESPACES$

namespace $NAMESPACE$
{ 
    public partial class $CLASSNAME$
    {
        protected readonly HttpClient _httpClient;

        public $CLASSNAME$(HttpClient httpClient)
        {
            _httpClient = httpClient;
        }

        $CLASSBODY$
    }
}
";

        public const string ClassTemplateWithNoDependency = @"
// <auto-generated>
//     This code was generated by HttpClientCodeGenerator.
// </auto-generated>

using System;
using System.Net.Http;
using System.Threading.Tasks;
using System.Collections.Generic;
$IMPORTNAMESPACES$

namespace $NAMESPACE$
{ 
    public partial class $CLASSNAME$
    {
        $CLASSBODY$
    }
}
";
    }
}
