name: Main

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore HttpClientCodeGenerator.sln
    - name: Build
      run: dotnet build HttpClientCodeGenerator.sln --no-restore --output ./bin
    - name: Test
      run: dotnet test HttpClientCodeGenerator.sln --verbosity normal
    - name: Deploy Package
      run: dotnet nuget push bin/*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NugetKey }} --skip-duplicate