name: Merge Request

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Install dependencies
      run: dotnet restore HttpClientCodeGenerator.sln
    - name: Build
      run: dotnet build HttpClientCodeGenerator.sln --configuration Release --no-restore --output ./bin
    - name: Test
      run: dotnet test HttpClientCodeGenerator.sln --verbosity normal